apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-core-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-core
  template:
    metadata:
      labels:
        app: ai-core
    spec:
      containers:
        - name: ai-core
          image: kartavya17/codescribe-ai-core
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-core
spec:
  selector:
    app: ai-core
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
