# .github/workflows/ci.yml
name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/codescribe-frontend:latest

      - name: Build and push Gateway image
        uses: docker/build-push-action@v4
        with:
          context: ./services/gateway
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/codescribe-gateway:latest

      - name: Build and push AI Core image
        uses: docker/build-push-action@v4
        with:
          context: ./services/ai-core
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/codescribe-ai-core:latest
